### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [azinke/MPU60x0#4]
In the file "MPU60x0/MPU60x0.cpp" there is a `Wire.endTransmission()` after the `Wire.requestFrom()`. You may remove those `Wire.endTransmission()`. They are at this moment at line 59 and 82.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

In the header of that file is the date 2019, that should be 2018?

The `_readBytes()` uses a Repeated Start, but the function `_read()` does not. You can make the `_read()` use a Repeated Start with `Wire.endTransmission(false);` (parameter 'false' instead of 'true').

**Comment by azinke** [comment]
Thanks very much for taking your time to have a glance on this project. It's pleasureful. I'll be really happy to get more feedback from you on it. Thanks.
